In [ ]:
# import libraries
import pandas as pd
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import ttest_ind
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler, MinMaxScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, make_scorer, f1_score
from sklearn.metrics import confusion_matrix

### Flagging Vendor Invoices for Manual Review
    Objective - Predict whether a vendor invoice should be flagged for manual approval based on abnormal cost, freight or deleivery patterns in order to reduce financial risks, improve operational efficiency and priotize human review where it adds the most value.

    1. Manual Invoice review is time consuming and does not scale with transaction volume
    2. An automatic flag reviiew system enables finance teams to focus attention on high risk invoices while allowing low risk invoices to be processed automatically

In [94]:
conn = sqlite3.connect("C:/Users/Tanushree/OneDrive/Desktop/portfolio_projects/ml_proj/data/inventory.db")

In [95]:
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type = 'table'", conn)
tables

              name
0        purchases
1  purchase_prices
2   vendor_invoice
3  begin_inventory
4    end_inventory

In [96]:
for table in tables['name']:
    print("Table name: ",table)
    
    df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 5", conn)
    display(df)

Table name:  purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

Table name:  purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

Table name:  vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

Table name:  begin_inventory

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

Table name:  end_inventory

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

In [97]:
purchases_df = pd.read_sql_query("SELECT * FROM purchases",conn)
purchases_df.head()

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

In [98]:
purchases_df.dtypes

InventoryId           str
Store               int64
Brand               int64
Description           str
Size                  str
VendorNumber        int64
VendorName            str
PONumber            int64
PODate                str
ReceivingDate         str
InvoiceDate           str
PayDate               str
PurchasePrice     float64
Quantity            int64
Dollars           float64
Classification      int64
dtype: object

In [99]:
purchase_agg_df = pd.read_sql_query(
    """
    SELECT 
        p.PONumber,
        COUNT(DISTINCT p.Brand) AS total_brands,
        SUM(p.Quantity) AS total_quantity,
        SUM(p.Dollars) AS total_item_dollars,
        AVG (julianday(p.ReceivingDate) - julianday(p.PODate)) AS avg_receiving_delay 
    FROM purchases p
    GROUP BY PONumber
    """,conn
)

In [100]:
purchase_agg_df.shape

(5543, 5)

In [101]:
pd.read_sql_query(
    """
    SELECT 
        vi.Quantity AS invoice_quantity,
        vi.Dollars AS invoice_dollars,
        vi.Freight,
        julianday(vi.InvoiceDate) - julianday(vi.PODate) AS days_po_to_invoice,
        julianday(vi.PayDate) - julianday(vi.InvoiceDate) AS days_to_pay
    FROM vendor_invoice vi
    """,conn
)

,invoice_quantity,invoice_dollars,Freight,days_po_to_invoice,days_to_pay
0,6,214.26,3.47,14.0,43.0
1,15,140.55,8.57,16.0,45.0
2,5,106.60,4.61,16.0,38.0
3,10100,137483.78,2935.20,23.0,24.0
4,1935,15527.25,429.20,14.0,36.0
...,...,...,...,...,...
5538,90,1563.00,8.60,16.0,35.0
5539,4617,37300.48,186.50,18.0,39.0
5540,9848,202815.78,932.95,11.0,33.0
5541,24747,149007.56,819.54,14.0,36.0
5542,437,3608.11,16.60,18.0,38.0

In [102]:
master_df = pd.read_sql_query(
    """
    WITH purchase_agg AS(
      SELECT 
          p.PONumber,
          COUNT(DISTINCT p.Brand) AS total_brands,
          SUM(p.Quantity) AS total_item_quantity,
          SUM(p.Dollars) AS total_item_dollars,
          AVG (julianday(p.ReceivingDate) - julianday(p.PODate)) AS avg_receiving_delay 
        FROM purchases p
        GROUP BY PONumber  
    )
    SELECT 
        vi.Quantity AS invoice_quantity,
        vi.Dollars AS invoice_dollars,
        vi.Freight,
        julianday(vi.InvoiceDate) - julianday(vi.PODate) AS days_po_to_invoice,
        julianday(vi.PayDate) - julianday(vi.InvoiceDate) AS days_to_pay,
        pa.total_brands,
        pa.total_item_quantity,
        pa.total_item_dollars,
        pa.avg_receiving_delay
    FROM vendor_invoice vi

    LEFT JOIN purchase_agg pa
    ON vi.PONumber = pa.PONumber
    """,
    conn
)

In [103]:
master_df.head()

,invoice_quantity,invoice_dollars,Freight,days_po_to_invoice,days_to_pay,total_brands,total_item_quantity,total_item_dollars,avg_receiving_delay
0,6,214.26,3.47,14.0,43.0,1,6,214.26,12.000000
1,15,140.55,8.57,16.0,45.0,2,15,140.55,10.333333
2,5,106.60,4.61,16.0,38.0,1,5,106.60,9.000000
3,10100,137483.78,2935.20,23.0,24.0,81,10100,137483.78,12.614130
4,1935,15527.25,429.20,14.0,36.0,29,1935,15527.25,8.752809

In [104]:
master_df.isnull().sum()

invoice_quantity       0
invoice_dollars        0
Freight                0
days_po_to_invoice     0
days_to_pay            0
total_brands           0
total_item_quantity    0
total_item_dollars     0
avg_receiving_delay    0
dtype: int64

In [105]:
master_df.dtypes

invoice_quantity         int64
invoice_dollars        float64
Freight                float64
days_po_to_invoice     float64
days_to_pay            float64
total_brands             int64
total_item_quantity      int64
total_item_dollars     float64
avg_receiving_delay    float64
dtype: object

In [106]:
def create_invoice_risk_label(row):

    # Invoice total mismatch with item-level total
    if (abs(row['invoice_dollars'] - row['total_item_dollars']) > 5):
        return 1

    # Abnormally high receiving delay
    if row['avg_receiving_delay'] > 10:
        return 1

    return 0

master_df['flag_invoice'] = master_df.apply(create_invoice_risk_label, axis = 1)
master_df['flag_invoice'].value_counts()

flag_invoice
0    3693
1    1850
Name: count, dtype: int64

In [107]:
flagged = master_df[master_df['flag_invoice'] == 1]
normal = master_df[master_df['flag_invoice'] == 0]

In [108]:
significant_features = []
non_significant_features = []
results = []

In [109]:
metrics = ['invoice_quantity', 'invoice_dollars', 'Freight', 'days_po_to_invoice',
           'days_to_pay', 'total_brands', 'total_item_quantity','total_item_dollars',
           'avg_receiving_delay']

In [110]:
for metric in metrics:
    flagged_mean = flagged[metric].mean()
    normal_mean = normal[metric].mean()

    t_stat, p_value = ttest_ind(
        flagged[metric].dropna(),
        normal[metric].dropna(),
        equal_var = False
    )

    if p_value < 0.05:
        significant_features.append(metric)
        results.append({
            "metric" : metric,
            "flagged_mean" : flagged_mean.round(2),
            "normal_mean" : normal_mean.round(2),
            "p_value" : p_value.round(3)
    })

    else:
        non_significant_features.append(metric)
        print(metric)

        print({
            "metric" : metric,
            "flagged_mean" : flagged_mean.round(2),
            "normal_mean" : normal_mean.round(2),
            "p_value" : p_value.round(3)
        })

days_to_pay
{'metric': 'days_to_pay', 'flagged_mean': np.float64(35.42), 'normal_mean': np.float64(35.49), 'p_value': np.float64(0.692)}
total_brands
{'metric': 'total_brands', 'flagged_mean': np.float64(42.29), 'normal_mean': np.float64(40.82), 'p_value': np.float64(0.508)}

In [111]:
non_significant_features

['days_to_pay', 'total_brands']

In [112]:
significant_features

['invoice_quantity',
 'invoice_dollars',
 'Freight',
 'days_po_to_invoice',
 'total_item_quantity',
 'total_item_dollars',
 'avg_receiving_delay']

In [113]:
results

[{'metric': 'invoice_quantity',
  'flagged_mean': np.float64(6728.28),
  'normal_mean': np.float64(5723.55),
  'p_value': np.float64(0.021)},
 {'metric': 'invoice_dollars',
  'flagged_mean': np.float64(65600.61),
  'normal_mean': np.float64(54302.64),
  'p_value': np.float64(0.008)},
 {'metric': 'Freight',
  'flagged_mean': np.float64(334.02),
  'normal_mean': np.float64(276.89),
  'p_value': np.float64(0.008)},
 {'metric': 'days_po_to_invoice',
  'flagged_mean': np.float64(17.23),
  'normal_mean': np.float64(16.02),
  'p_value': np.float64(0.0)},
 {'metric': 'total_item_quantity',
  'flagged_mean': np.float64(6728.28),
  'normal_mean': np.float64(5723.55),
  'p_value': np.float64(0.021)},
 {'metric': 'total_item_dollars',
  'flagged_mean': np.float64(65600.61),
  'normal_mean': np.float64(54302.64),
  'p_value': np.float64(0.008)},
 {'metric': 'avg_receiving_delay',
  'flagged_mean': np.float64(8.47),
  'normal_mean': np.float64(7.27),
  'p_value': np.float64(0.0)}]

In [114]:
# Separate features and target (Safely removing the leakage columns)
X = master_df[["invoice_quantity", "Freight", "days_po_to_invoice", "total_item_quantity"]]
y = master_df["flag_invoice"]

In [115]:
X.describe().round().T

,count,mean,std,min,25%,50%,75%,max
invoice_quantity,5543.0,6059.0,14453.0,1.0,83.0,423.0,5100.0,141660.0
Freight,5543.0,296.0,714.0,0.0,5.0,25.0,230.0,8468.0
days_po_to_invoice,5543.0,16.0,3.0,9.0,14.0,16.0,19.0,23.0
total_item_quantity,5543.0,6059.0,14453.0,1.0,83.0,423.0,5100.0,141660.0

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

In [117]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [118]:
model1 = LogisticRegression(random_state = 42)
model1.fit(X_train_scaled, y_train)

LogisticRegression(random_state=42)

In [119]:
model2 = DecisionTreeClassifier(random_state = 42)
model2.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [120]:
model3 = RandomForestClassifier(random_state = 42)
model3.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [121]:
def evaluate_model(model_variable, X_test_data, y_test_data, model_name):

    predictions = model_variable.predict(X_test_data)
    
    print(f"\nMODEL: {model_name}")
    print(f"Accuracy Score: {accuracy_score(y_test_data, predictions):.2f}")
    print("\nClassification Report:")
    print(classification_report(y_test_data, predictions))

In [122]:
evaluate_model(model1, X_test_scaled, y_test, 'Logistic Regression')
evaluate_model(model2, X_test, y_test, 'Descision Tree Classifier')
evaluate_model(model3, X_test, y_test, 'Random Forest Classifier')

MODEL: Logistic Regression
Accuracy Score: 0.66

Classification Report:
              precision    recall  f1-score   support

           0       0.66      0.98      0.79       725
           1       0.56      0.05      0.09       384

    accuracy                           0.66      1109
   macro avg       0.61      0.51      0.44      1109
weighted avg       0.63      0.66      0.55      1109


MODEL: Descision Tree Classifier
Accuracy Score: 0.81

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.87      0.86       725
           1       0.74      0.70      0.71       384

    accuracy                           0.81      1109
   macro avg       0.79      0.78      0.79      1109
weighted avg       0.81      0.81      0.81      1109


MODEL: Random Forest Classifier
Accuracy Score: 0.87

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.96      0.90       725
           1       0.90      0.69      0.78       384

    accuracy                           0.87      1109
   macro avg       0.88      0.82      0.84      1109
weighted avg       0.87      0.87      0.86      1109

In [123]:
feature_importance = pd.DataFrame({
    "feature" : X_train.columns,
    "importance" : model3.feature_importances_
}).sort_values(by="importance", ascending=False)

feature_importance

               feature  importance
3  total_item_quantity    0.427217
0     invoice_quantity    0.260562
1              Freight    0.222804
2   days_po_to_invoice    0.089417

In [124]:
X = master_df[["invoice_quantity", "Freight", "total_item_quantity"]]
y = master_df['flag_invoice']

In [131]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model3 = RandomForestClassifier(random_state = 42)
model3.fit(X_train, y_train)

def evaluate_model(model_variable, X_test_data, y_test_data, model_name):

    predictions = model_variable.predict(X_test_data)
    
    print(f"\nMODEL: {model_name}")
    print(f"Accuracy Score: {accuracy_score(y_test_data, predictions):.2f}")
    print("\nClassification Report:")
    print(classification_report(y_test_data, predictions))


evaluate_model(model3, X_test, y_test, 'Random Forest Classifier')

MODEL: Random Forest Classifier
Accuracy Score: 0.86

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.95      0.90       725
           1       0.88      0.71      0.78       384

    accuracy                           0.86      1109
   macro avg       0.87      0.83      0.84      1109
weighted avg       0.87      0.86      0.86      1109

In [138]:
rf = RandomForestClassifier(random_state = 42, n_jobs = 1)

param_grid = {
    "n_estimators" : [100, 200, 300],
    "max_depth" : [None, 4, 5, 6],
    "min_samples_split" : [2, 3, 5],
    "min_samples_leaf" : [1, 2, 5],
    "criterion" : ["gini", "entropy"]
}

scorer = make_scorer(f1_score)

grid_search = GridSearchCV(
    estimator = rf,
    param_grid = param_grid,
    scoring = scorer,
    cv = 5,
    verbose = 1,
    n_jobs = 5
)

grid_search.fit(X_train,y_train)
evaluate_model(grid_search, X_test, y_test, 'Random Forest Classifier')

Fitting 5 folds for each of 216 candidates, totalling 1080 fits

MODEL: Random Forest Classifier
Accuracy Score: 0.87

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.96      0.91       725
           1       0.91      0.69      0.79       384

    accuracy                           0.87      1109
   macro avg       0.88      0.83      0.85      1109
weighted avg       0.87      0.87      0.86      1109

In [139]:
for param, value in grid_search.best_params_.items():
    print(f"{param} : {value}")

criterion : gini
max_depth : None
min_samples_leaf : 1
min_samples_split : 5
n_estimators : 300

In [145]:
print("Baseline Model:")
print(confusion_matrix(y_test, model3.predict(X_test)))

Baseline Model:
[[688  37]
 [113 271]]

In [147]:
print("Tuned Grid Search:")
print(confusion_matrix(y_test, grid_search.predict(X_test)))

Tuned Grid Search:
[[699  26]
 [119 265]]